#!/usr/bin/env python3
"""Auto-generated by ActiveLearningAgent."""
import argparse
from agents.active_learning.active_learning_agent import run_training_job


def main() -> int:
    parser = argparse.ArgumentParser(description='Run active-learning training job')
    parser.add_argument('--config', required=True, help='Path to training job config JSON')
    args = parser.parse_args()
    run_training_job(args.config)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
